### ISSUE TITLE
Seriously inefficient construct

### ISSUE THREAD

**Issue by viamage** [lilessam/mailsender#1]
```
foreach($users_ids as $user_id){
    $user = User::where('id', $user_id->user_id)->first();
```

You are aware that with 1000 users this will make 1000 sql queries for each email sent? Never query in loop! You don't use background jobs here so with bigger users table it will surely end up with gateway timeout error.

![protip](https://i.viamage.com/jz/screen-2018-06-11-12-44-34.png)

**Comment by AhmedEssamElNaggar** [comment]
Absolutely TRUE!
Thanks for sharing that.
It's been resolved in commit [#914e203](https://github.com/lilessam/mailsender/commit/db031fd2c1352b8ee6eda76d47c9a424aa06dc5c)
